### ISSUE TITLE
How to start scheduler?

### ISSUE THREAD

**Issue by estebanbouza** [JustinAiken/active_scheduler#11]
How is active scheduler supposed to be started after being configured? I'm using Rails 5. is it through `rails resque:scheduler` ?

**Comment by JustinAiken** [comment]
`active_scheduler` isn't an actual service than runs; it just adapts a resque config format into an activejob format.  So you run the scheduler the same way you would with this gem - whether it be via foreman, upstart, it's own docker container, etc...   This library just lets you use `ActiveJob`-friendly workers instead of `Resque` workers.
